# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and Deploy Python App to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - prod  # Trigger on pushes to prod branch


jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runners

    steps:
      - uses: actions/checkout@v4  # Checkout the code

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs (optional)
        uses: actions/upload-artifact@v4
        with:
          name: python-app  # Optional: Upload artifact for potential future deployment jobs
          path: |
            release.zip
            !venv/

      - name: Announcerr
        if: ${{ github.ref == 'refs/heads/prod' }}  # Only run for prod branch
        uses: singhkshitij/announcerr@v2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Production Build Ready for Deployment"
          body: "The production code has been successfully built and is ready for deployment. Please deploy it to the production environment manually."
          to: shubhanginannaware1155@gmail.com 
          from: mysticSync # <kshitij@mytrashcode.com>

      


      # - name: Send Email
      #   uses: hilarion5/send-mail@v1
      #   with:
      #     smtp-server: ${{ secrets.SMTP_SERVER }}
      #     smtp-port: 587
      #     smtp-secure: true
      #     from-email: mysticsync.inc@gmail.com
      #     to-email: mahajandhiru001@gmail.com
      #     username: ${{ secrets.SMTP_USER }}
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Test Email
      #     body: This is a test email sent from GitHub Actions.
  # notif:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Send Email Notifications
  #       uses: danthe1st/email-filechange-notif-action@v1
  #       with:
  #         senderEmail: "mysticsync.inc@gmail.com"
  #         subjectLine: "GitHub file change notification"
  #         mailingList: "mahajandhiru001@gmail.com"
  #         smtpServer: ${{ secrets.SMTP_SERVER }}
  #         smtpPort: 587
  #         smtpUsername: ${{ secrets.SMTP_USER }}
  #         smtpPassword: ${{ secrets.SMTP_PASSWORD }}
