name: Build and deploy Python app to Azure Web App - Prod-DTest

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

      - name: Display structure of downloaded files
        run: ls -R

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_89D17418D7154399B2EB86B612EF2AD1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AD37AB9BA9D04288BD3A4183F508CCC4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F83FB678DB96471DB3E918BE8DA780A3 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Prod-DTest'
          slot-name: 'Production'

