name: Manual Deployment to Azure Web App (Prod)

on:
  workflow_dispatch:
  push:
    branches:
      - prod # Trigger on pushes to prod branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/

      - name: Unzip artifact for deployment
        run: unzip build/release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CC34A95A9DD54D67841EB327044A5352 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B64F932053FC4BD98E166E39CAF2DAA9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3196DCF9FDE04EA39884F06CE5173D7D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "Prod-DTest"
          slot-name: "Production"
          package: build/

